---
name: Micropolis for Unity
description: Unity version of Micropolis rewritten from the ground up
url: https://bsimser.github.io/Micropolis
repository: https://github.com/bsimser/Micropolis
show_downloads: true
twitter:
  username: bsimser
theme: jekyll-theme-architect
site.github.zip_url: https://github.com/bsimser/Micropolis/archive/develop.zip

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-mentions
